handle spaces in .env files, check DEVOPS settings

diff --git a/load-profile b/load-profile
--- a/load-profile
+++ b/load-profile
@@ -12,22 +12,94 @@ fi
 function trace
 {
 if [ $DEVOPS_DEBUG ]; then
-    echo $@
+    echo >&2 $@
 fi
 }
 
-# also consider using a function 
-# http://stackoverflow.com/questions/5777170/substitution-with-sed-bash-function
-# TODO: give argument of valid template args.
+function raw_content
+{
+    cat $1 | sed '/^\s*$/d'| grep -v ^#
+}
+
+function expanded_content
+{
+    cat $1 \
+     | sed 's/{{[[:blank:]]*profile_home[[:blank:]]*}}/_profile_hometest_/'  \
+     | sed 's/{{[[:blank:]]*/[[/' \
+     | sed 's/[[:blank:]]*}}/]]/' \
+     | sed '/^[[:blank:]]*$/d' \
+     | sed '/^[[:blank:]]*#.*/d'
+}  
+
+function content
+{
+    if [ $DEVOPS_NOEXPAND ]; then
+        raw_content $1
+    else
+        expanded_content $1
+    fi
+}
+
+function dump
+{
+    if [ $DEVOPS_EXPORT ]; then
+        if [ ! $DEVOPS_NOHEADERS ]; then
+            echo "[$(basename $1)]"
+            content $1
+            echo ""
+        else
+            content $1
+        fi
+    fi
+}
+
+function dump_meta
+{
+    if [ $DEVOPS_EXPORT ]; then
+        if [ ! $DEVOPS_NOHEADERS ]; then
+            echo "[meta]"
+        fi
+        if [ $DEVOPS_NOEXPAND ]; then
+            echo "DEVOPS_PROFILE_ROOT={{ profile_root }}"
+            echo "DEVOPS_PROFILE_HOME={{ profile_home }}"
+        else
+            echo "DEVOPS_PROFILE_ROOT=${DEVOPS_PROFILE_ROOT}"
+            echo "DEVOPS_PROFILE_HOME=${DEVOPS_PROFILE_HOME}"
+        fi
+        echo "DEVOPS_PROFILE=${DEVOPS_PROFILE}"
+        if [ $DEVOPS_NOEXPAND ]; then
+            echo "DEVOPS_SYSTEM_ROOT={{ system_root }}"
+            echo "DEVOPS_SYSTEM_HOME={{ system_home }}"
+        else
+            echo "DEVOPS_SYSTEM_ROOT=${DEVOPS_SYSTEM_ROOT}"
+            echo "DEVOPS_SYSTEM_HOME=${DEVOPS_SYSTEM_HOME}"
+        fi
+        echo "DEVOPS_SYSTEM=${DEVOPS_SYSTEM}"
+    fi
+}
+
 function process
 {
-    trace "searching: $1"
     if [ -e "$1" ]; then
         trace "processing: $1"
         set -e
-        export $(cat $1 \
-            | sed 's/{{ profile_home }}/redacted-for-test/'  \
-            | grep -v ^# | xargs)
+        if [ -n "$DEVOPS_OUTPUT" ]; then
+            dump $1 > $DEVOPS_OUTPUT
+        else
+            dump $1
+        fi
+
+        # We need to find DEVOPS_PROFILE or DEVOPS_SYSTEM, even if we only export
+        # the following xargs solution is elegant, but breaks on spaces, even quoted.
+        # export  $(expanded_content $1 | xargs )
+        # other solutions break because export must not be in a subshell
+        # the following works ... sigh
+        old_IFS=$IFS; IFS=$'\n'
+        # TODO: check that there are no unsupported templates
+        for line in $(expanded_content $1); do export "$line"; done 
+        IFS=$old_IFS
+        [ -z "$DEVOPS_PROFILE_HOME" ] || echo >&2 "warning: DEVOPS_PROFILE_HOME canot be set in $(basename $1)\n- it is a computed value"
+        [ -z "$DEVOPS_SYSTEM_HOME" ] || echo >&2 "warning: DEVOPS_SYSTEM_HOME can never set in $(basename $1)\n- it is a computed value"
     else
         trace "skipping: $1"
     fi
@@ -47,24 +119,88 @@ function check
     fi
 }
 
-# see bin/help run
-# for specfication
-export DEVOPS_PROFILE_ROOT=${DEVOPS_PROFILE_ROOT:-${HOME}/.devops/profiles}
-check DEVOPS_PROFILE_ROOT ${DEVOPS_PROFILE_ROOT}
-process "${DEVOPS_PROFILE_ROOT}/common_profile.env"
+# In general values are set by the user in the environment,
+# but all values can be set in a subshell of the profiled
+# environment. In this case the settings in .env files
+# will not be active. While an accidental implication,
+# it also seems the best thing to do.
 
-export DEVOPS_PROFILE=${DEVOPS_PROFILE:-""}
-export DEVOPS_PROFILE_HOME=${DEVOPS_PROFILE_ROOT}/${DEVOPS_PROFILE}
-check DEVOPS_PROFILE_HOME ${DEVOPS_PROFILE_ROOT}
-process "${DEVOPS_PROFILE_HOME}/profile.env"
+# Pick up from environment unless command line already overrides.
+OVERRIDE_DEVOPS_PROFILE_ROOT=${OVERRIDE_DEVOPS_PROFILE_ROOT:-${DEVOPS_PROFILE_ROOT:-""}}
+OVERRIDE_DEVOPS_PROFILE=${OVERRIDE_DEVOPS_PROFILE:-${DEVOPS_PROFILE:-""}}
+OVERRIDE_DEVOPS_SYSTEM=${OVERRIDE_DEVOPS_SYSTEM:-${DEVOPS_SYSTEM:-""}}
+OVERRIDE_DEVOPS_SYSTEM_ROOT=${OVERRIDE_DEVOPS_SYSTEM_ROOT:-${DEVOPS_SYSTEM_ROOT:-""}}
 
-export DEVOPS_SYSTEM_ROOT=${DEVOPS_SYSTEM_ROOT:-$(pwd)/systems}
-check DEVOPS_SYSTEM_ROOT ${DEVOPS_SYSTEM_ROOT}
-process ${DEVOPS_SYSTEM_ROOT}/common_system.env
+unset DEVOPS_PROFILE_ROOT
+unset DEVOPS_PROFILE_HOME
+unset DEVOPS_PROFILE
+unset DEVOPS_SYSTEM_ROOT
+unset DEVOPS_SYSTEM_HOME
+unset DEVOPS_SYSTEM
 
-export DEVOPS_SYSTEM=${DEVOPS_SYSTEM:-""}
-export DEVOPS_SYSTEM_HOME=${DEVOPS_SYSTEM_ROOT}/${DEVOPS_SYSTEM}
-check DEVOPS_SYSTEM_HOME ${DEVOPS_SYSTEM_ROOT}/${DEVOPS_SYSTEM}
-process ${DEVOPS_SYSTEM_HOME}/system.env
+OVERRIDE_DEVOPS_PROFILE_ROOT=${OVERRIDE_DEVOPS_PROFILE_ROOT:-${HOME}/.devops/profiles}
+check DEVOPS_PROFILE_ROOT ${OVERRIDE_DEVOPS_PROFILE_ROOT}
+process "${OVERRIDE_DEVOPS_PROFILE_ROOT}/common_profile.env"
 
+[ -z "$DEVOPS_SYSTEM" ] || echo >&2 "warning: DEVOPS_SYSTEM cannot be set in 'common_profile.env'"
+OVERRIDE_DEVOPS_PROFILE=${OVERRIDE_DEVOPS_PROFILE:-${DEVOPS_PROFILE}}
+OVERRIDE_DEVOPS_SYSTEM=${OVERRIDE_DEVOPS_SYSTEM:-${DEVOPS_SYSTEM}}
+OVERRIDE_DEVOPS_SYSTEM_ROOT=${OVERRIDE_DEVOPS_SYSTEM_ROOT:-${DEVOPS_SYSTEM_ROOT}}
+unset DEVOPS_PROFILE
+unset DEVOPS_SYSTEM
+unset DEVOPS_SYSTEM_ROOT
+
+trace "DEVOPS_PROFILE=${OVERRIDE_DEVOPS_PROFILE}"
+sep=""
+[ -z "$OVERRIDE_DEVOPS_PROFILE" ] || sep="/"
+OVERRIDE_DEVOPS_PROFILE_HOME=${OVERRIDE_DEVOPS_PROFILE_ROOT}${sep}${OVERRIDE_DEVOPS_PROFILE}
+check DEVOPS_PROFILE_HOME ${OVERRIDE_DEVOPS_PROFILE_HOME}
+
+process "${OVERRIDE_DEVOPS_PROFILE_HOME}/profile.env"
+
+[ -z "$DEVOPS_PROFILE_ROOT" ] || echo >&2 "warning: DEVOPS_PROFILE_ROOT cannot be set in 'profile.env'"
+[ -z "$DEVOPS_PROFILE" ] || echo >&2 "warning: DEVOPS_PROFILE cannot be set in 'profile.env'"
+OVERRIDE_DEVOPS_SYSTEM_ROOT=${OVERRIDE_DEVOPS_SYSTEM_ROOT:-${DEVOPS_SYSTEM_ROOT}}
+OVERRIDE_DEVOPS_SYSTEM=${OVERRIDE_DEVOPS_SYSTEM:-${DEVOPS_SYSTEM}}
+unset DEVOPS_SYSTEM_ROOT
+unset DEVOPS_SYSTEM
+
+
+OVERRIDE_DEVOPS_SYSTEM_ROOT=${OVERRIDE_DEVOPS_SYSTEM_ROOT:-$(pwd)/systems}
+check DEVOPS_SYSTEM_ROOT ${OVERRIDE_DEVOPS_SYSTEM_ROOT}
+process ${OVERRIDE_DEVOPS_SYSTEM_ROOT}/common_system.env
+
+[ -z "$DEVOPS_PROFILE" ] || echo >&2 "warning: DEVOPS_PROFILE cannot be set in 'common_system.env'"
+[ -z "$DEVOPS_PROFILE_ROOT" ] || echo >&2 "warning: DEVOPS_PROFILE_ROOT cannot be set in 'common_system.env'"
+[ -z "$DEVOPS_SYSTEM_ROOT" ] || echo >&2 "warning: DEVOPS_SYSTEM_ROOT cannot be set in 'common_system.env'"
+[ -z "$DEVOPS_PROFILE" ] || echo >&2 "warning: DEVOPS_PROFILE cannot be set in 'common_system.env'"
+
+# Allow system to be selected in common_profile.env.
+OVERRIDE_DEVOPS_SYSTEM=${OVERRIDE_DEVOPS_SYSTEM:-${DEVOPS_SYSTEM}}
+unset DEVOPS_SYSTEM
+
+sep=""
+[ -z "$OVERRIDE_DEVOPS_SYSTEM" ] || sep="/"
+trace "DEVOPS_PROFILE=${OVERRIDE_DEVOPS_PROFILE}"
+OVERRIDE_DEVOPS_SYSTEM_HOME=${OVERRIDE_DEVOPS_SYSTEM_ROOT}${sep}${OVERRIDE_DEVOPS_SYSTEM}
+check DEVOPS_SYSTEM_HOME ${OVERRIDE_DEVOPS_SYSTEM_HOME}
+process ${OVERRIDE_DEVOPS_SYSTEM_HOME}/system.env
+
+[ -z "$DEVOPS_PROFILE_ROOT" ] || echo >&2 "warning: DEVOPS_PROFILE_ROOT cannot be set in 'system.env'"
+[ -z "$DEVOPS_SYSTEM_ROOT" ] || echo >&2 "warning: DEVOPS_SYSTEM_ROOT cannot be set in 'system.env'"
+[ -z "$DEVOPS_PROFILE" ] || echo >&2 "warning: DEVOPS_PROFILE cannot be set in 'system.env'"
+[ -z "$DEVOPS_SYSTEM" ] || echo >&2 "warning: DEVOPS_SYSTEM cannot be set in 'system.env'"
+
+export DEVOPS_PROFILE_ROOT=${OVERRIDE_DEVOPS_PROFILE_ROOT}
+export DEVOPS_PROFILE_HOME=${OVERRIDE_DEVOPS_PROFILE_HOME}
+export DEVOPS_PROFILE=${OVERRIDE_DEVOPS_PROFILE}
+export DEVOPS_SYSTEM_ROOT=${OVERRIDE_DEVOPS_SYSTEM_ROOT}
+export DEVOPS_SYSTEM_HOME=${OVERRIDE_DEVOPS_SYSTEM_HOME}
+export DEVOPS_SYSTEM=${OVERRIDE_DEVOPS_SYSTEM}
+
+if [ -n "$DEVOPS_OUTPUT" ]; then
+    dump_meta > $DEVOPS_OUTPUT
+else
+    dump_meta
+fi
 
diff --git a/run-profile b/run-profile
--- a/run-profile
+++ b/run-profile
@@ -23,6 +23,21 @@ options :
     --system  | -s <system>
             override DEVOPS_SYSTEM
 
+    --export  | -e
+            expands and exports .env files with '[<basename>]' as separator
+            (commands are not alloved)
+
+    --no-expand | -n
+            disables template expansion
+            implies -e
+
+    --no-headers | -x
+            disables section headers in export
+            implies -e
+        
+    --output  | -o <file>
+            implies -e but writes to specified file
+
     --force   | -f
             ignore missing directory errors
 
@@ -108,12 +123,19 @@ function help
 # we cannot use this directly - we must stop at a command and fail at unknown option
 # then collect the remains for the subcommand - but it is nice base.
 
+#TODO:
+echo >&2 "warning: option parsing not yet solid"
+
+OVERRIDE_DEVOPS_PROFILE=${DEVOPS_PROFILE}
+OVERRIDE_DEVOPS_SYSTEM=${DEVOPS_SYSTEM}
+
 STD_IN=0
 
 prefix=""
 key=""
 value=""
-while [ ! -z "$1" ]
+keyValue=$1
+while [ ! -z "$keyValue" ]
 do
   keyValue=$1
   case "${prefix}${keyValue}" in
@@ -121,22 +143,30 @@ do
     --help)             key="-H";     value=1;;
     -p=*|--profile=*)   key="-p";     value="${keyValue#*=}";;
     -s=*|--system=*)    key="-s";     value="${keyValue#*=}";;
+    -o=*|--output=*)    key="-o";     value="${keyValue#*=}";;
     -d|--debug)         key="-d";     value=1;;
+    -e|--export)        key="-e";     value=1;;
+    -n|--no-expand)     key="-n";     value=1;;
+    -x|--no-headers)    key="-x";     value=1;;
     -f|--force)         key="-f";     value=1;;
     -|--stdin)          key="-";      value=1;;
     --) shift; break;;
-    -*) fail "error: bad option: $1";;
+    -*) fail "error: bad option: $1";; # TODO: likely wrong value displayed in some cases
     *) break;; 
   esac
   shift
   case $key in
     -h) short_help; exit 0;;
     -H) help; exit 0;;
-    -p) export DEVOPS_PROFILE="${value}";         prefix=""; key="";;
-    -s) export DEVOPS_SYSTEM="${value}";          prefix=""; key="";;
-    -d) export DEVOPS_DEBUG="${value}";           prefix=""; key="";;
-    -f) export DEVOPS_FORCE="${value}";           prefix=""; key="";;
-    -)  STD_IN=${value};                          prefix=""; key="";; 
+    -p) OVERRIDE_DEVOPS_PROFILE="${value}"; prefix=""; key="";;
+    -s) OVERRIDE_DEVOPS_SYSTEM="${value}"; prefix=""; key="";;
+    -d) DEVOPS_DEBUG="${value}"; prefix=""; key="";;
+    -e) DEVOPS_EXPORT="${value}"; prefix=""; key="";;
+    -o) DEVOPS_OUTPUT="${value}"; DEVOPS_EXPORT=1; prefix=""; key="";;
+    -n) DEVOPS_NOEXPAND="${value}"; DEVOPS_EXPORT=1; prefix=""; key="";;
+    -x) DEVOPS_NOHEADERS="${value}"; DEVOPS_EXPORT=1; prefix=""; key="";;
+    -f) DEVOPS_FORCE="${value}"; prefix=""; key="";;
+    -)  STD_IN=${value}; prefix=""; key="";; 
     *)  prefix="${keyValue}=";;
   esac
 done
@@ -150,7 +180,11 @@ fi
 if [ -z "$1" ]; then
     CMD=env
 else
-    CMD=$@
+    if [ ! $DEVOPS_EXPORT ]; then
+        CMD=$@
+    else
+        fail "command not allowed with any export option: $1"
+    fi
 fi
 
 # http://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
@@ -158,10 +192,9 @@ fi
 command -v $1 >/dev/null 2>&1 || fail "error: command not found: $1"
 
 
-# TEST CODE  /  INCOMPLETE CODE
-
 source `dirname $0`/load-profile
 
-echo test: ec2 ini path: ${EC2_INI_PATH}
-$CMD
+if [ ! $DEVOPS_EXPORT ]; then
+    $CMD
+fi
 
