fix quoting bugs in opt parser

diff --git a/run-profile b/run-profile
--- a/run-profile
+++ b/run-profile
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 
 # ----------------------------------------------------------------------
 # dev_ops run_profile tool 'rp' (c) 2014, Mikkel Fahnøe Jørgensen,
@@ -243,8 +243,9 @@ function document {
 # opt_in
 # for arg
 # do
-#   if opt_next $arg; then
-#   case arg
+#   NOTE: very important to quote "$arg"
+#   if opt_next "$arg"; then
+#   case "$arg"
 #     # flag option:
 #     -v | --verbose) opt_f -v;;
 #
@@ -317,7 +318,7 @@ function document {
 # unset MY_OUTPUT; unset MY_VERBOSE;
 # for arg
 # do
-#   case arg
+#   case "$arg"
 #     # perhaps also test for empty value from -o ""
 #     -o) MY_OUTPUT=$2; shift;; 
 #     -v) MY_VERBOSE=1;;
@@ -334,6 +335,9 @@ function document {
 
 # TODO: _opt_allow handles multiple short options, we have no implemention for that yet.
 
+# NOTE: it is exceedingly important to pass parameters in quoted expansions like "$arg",
+# otherwise string content can and will get lost.
+
 # Override this function as needed before calling opt_in.
 # Possible 'reason' values: "missing-option" | "bad-option".
 function opt_user_fail { reason=$1; msg=$2; name=$3; echo >&2 "$msg $name"; exit $E_BAD_ARGS; }
@@ -346,11 +350,11 @@ function opt_missing { opt_user_fail "missing-option" $_opt_expect "error: optio
 # Parsing output: builds a new commandlines in "args", expect the original $@ _opt_tokens to be set
 # one at a time and called with the appropriate parser interface function.
 function _opt_esc() { echo "escaping: ($1)"
-_opt_qv=${1//\\/\\\\}; _opt_qv=${_opt_qv//"/\\"}; _opt_qv=${_opt_qv//'/\\'}; _opt_qv="\"${_opt_qv}\"";
+_opt_qv="${1//\\/\\\\}"; _opt_qv="${_opt_qv//"/\\"}"; _opt_qv="${_opt_qv//'/\\'}"; _opt_qv="\"${_opt_qv}\"";
 echo "escaped: ($_opt_qv)"; }
 function _opt_put { echo "put $1 ($opt_expect)"; [ -n "$_opt_expect" ] && opt_missing || _opt_args="${_opt_args}$1 $2"; }
 function _opt_put_pos { _opt_args="${_opt_args}$1 "; [ -n "$_opt_expect" ] || _opt_brk=1; unset _opt_expect; _opt_allow=0; }
-function _opt_put_vopt { _opt_esc $2; _opt_put $1 "$_opt_qv "; _opt_allow=0; }
+function _opt_put_vopt { _opt_esc "$2"; _opt_put $1 "$_opt_qv "; _opt_allow=0; }
 
 
 # Comments are just examples:
@@ -373,7 +377,7 @@ function opt_f { echo "o -$1, "; _opt_put $1; _opt_allow=1; }
 # Either an expected value following opt_ev, and otherwise a call to opt_pos
 # will break token parsing and pass on values until opt_resume is found, or
 # opt_out stops the processing.
-function opt_pos { echo "p, "; [ -z "$_opt_expect" ] && _opt_brk=1 && echo "brk"; _opt_esc $_opt_token; _opt_put_pos $_opt_qv; }
+function opt_pos { echo "p, "; [ -z "$_opt_expect" ] && _opt_brk=1 && echo "brk"; _opt_esc "$_opt_token"; _opt_put_pos "$_opt_qv"; }
 
 # -- breaks option parsing, but is passed on, anything after is passed to opt_pos
 # but it does not have to --, it could be a keyword
@@ -387,7 +391,9 @@ function opt_resume { _opt_brk=0; }
 
 # Assigns the token to be parse and # consumes tokens automatically
 # if the _opt_brk flag has been set.
-function opt_next { _opt_token=$1; if [ $_opt_brk -eq 0 ]; then return 0; else opt_pos; return 1; fi; }
+function opt_next { _opt_token="$1"; 
+echo "next token: >$_opt_token<";
+if [ $_opt_brk -eq 0 ]; then return 0; else opt_pos; return 1; fi; }
 
 function opt_debug { echo >&2 "opt: token='$_opt_token'"; }
 
@@ -418,11 +424,20 @@ function opt_out {
 # ----------------------------------------------------------------------
 
 
+    echo "arg list:"
+    for arg
+    do
+        echo $arg
+    done
+    echo "end arg list."
+
 # customize opt_in error handler
 function opt_user_fail {
     reason=$1; name=$2; msg=$3;
     fail "$msg $name"
 }
+
+list_args $@
 
 opt_in
 
@@ -430,7 +445,7 @@ opt_in
 for arg
 do
     # else branch collects args after last option
-    if opt_next $arg; then
+    if opt_next "$arg"; then
     case "$arg" in
        # TODO: it won't work, we need to parse this in opt_pos
        #d|e|f|h|n|v|x) moropt_ev;;
@@ -470,12 +485,19 @@ done
 
 echo "args before long translation:\n$@"
 echo "args string after translation:\n$_opt_args"
-opt_out
-eval "set -- $OPT_ARGS"
+opt_out && eval "set -- $OPT_ARGS" || fail "internal: option parsing error"
+
 
 # put the translated arguments back on the input
 echo "args after long translation:\n$@"
-exit
+
+    echo "arg list:"
+    for arg
+    do
+        echo $arg
+    done
+    echo "end arg list."
+
 
 # Now do a program specific parse.
 # The follwoing will work without the former, but only
@@ -489,25 +511,25 @@ exit
 
 # Reset all variables that might be set
 
-e_arg=0
-f_arg=0
-n_arg=0
-v_arg=0
-x_arg=0
-o_arg=0
-p_arg=0
-s_arg=0
+unset e_arg
+unset f_arg
+unset n_arg
+unset v_arg
+unset x_arg
+unset o_arg
+unset p_arg
+unset s_arg
 
 o_val=""
 p_val=""
 s_val=""
 
 # STDIN (-)
-stdin_arg=0
+unset stdin_arg
 # (--) split operator
-split_arg=0
+unset split_arg
 # not option argument seen
-cmd_arg=0
+unset cmd_arg
 
 while [ -n "$1" ]
 do
@@ -529,6 +551,11 @@ do
     esac
     shift
 done
+
+# TODO: the following does not parse correctly:
+#  echo "\ _"
+#  echo "\ "
+#  echo ".\ ."
 
 echo "args left: $@"
 echo "done testing args"
@@ -619,7 +646,7 @@ fi
 # this method is Posix compliant.
 command -v $1 >/dev/null 2>&1 || fail "error: command not found: $1"
 
-
+trace "loading profile"
 source `dirname $0`/load-profile
 
 if [ ! $DEVOPS_EXPORT ]; then
